### ISSUE TITLE
Set minimum PHP version to 7.3

### ISSUE THREAD

**Issue by sandrokeil** [crazyxman/simdjson_php#12]
We can set the minimum PHP version to 7.3 for this extension. See [PHP Supported Versions](https://www.php.net/supported-versions)

**Comment by crazyxman** [comment]
If it does not rely on php7.3 features. It is not recommended to limit the version

**Comment by sandrokeil** [comment]
Since we have CI for all PHP 7 versions, I close this because there is no reason at the moment.
