### ISSUE TITLE
Missing depth argument definition in ZEND_BEGIN_ARG_INFO

### ISSUE THREAD

**Issue by sandrokeil** [crazyxman/simdjson_php#15]
It looks like the depth argument is missing in the [ZEND_BEGIN_ARG_INFO](https://github.com/crazyxman/simdjson_php/blob/master/simdjson.cpp#L38-L52) for the funtions `simdjson_key_value`, `simdjson_key_exists` and `simdjson_key_count`.

Should this be added or why is it not defined like for `simdjson_decode_arginfo`?

**Comment by crazyxman** [comment]
Yes, it should be consistent with simdjson_decode_arginfo
