### ISSUE TITLE
Prepare for setting this up as a PECL, check in package.xml?

### ISSUE THREAD

**Issue by TysonAndre** [crazyxman/simdjson_php#26]
I see build-packagexml.php but no package.xml.

- Make reporting bugs easier by making the release easier to identify
- Track the changelog in package.xml
- Indicate min/max supported php versions
- One of the comments on https://github.com/crazyxman/simdjson_php/issues/8 was that it couldn't be tried out without a PECL

**Comment by crazyxman** [comment]
@TysonAndre  Do you want to add a package.xml to it? Of course you can add it

**Comment by TysonAndre** [comment]
>Do you want to add a package.xml to it? Of course you can add it

Thanks, will do. I created this ticket since I wasn't familiar with how or why build-packagexml.php was currently used
