### ISSUE TITLE
Added php_info implementation line in php_simdjson.cpp breaks the compilation from source

### ISSUE THREAD

**Issue by vassil-velichkov** [crazyxman/simdjson_php#48]
This added line breaks the complication from source (Ubuntu 22.04.5 / GCC 11.2.0):
php_simdjson.cpp:250:61: error: ‘active_implementation’ is not a member of ‘simdjson’; did you mean ‘get_active_implementation’?
250 |     php_info_print_table_row(2, "Implementation", simdjson::active_implementation->description().c_str());

_Originally posted by @vassil-velichkov in https://github.com/crazyxman/simdjson_php/pull/44#discussion_r950624223_

**Comment by TysonAndre** [comment]
Yeah, it's a merge conflict from https://github.com/crazyxman/simdjson_php/pull/42 and https://github.com/crazyxman/simdjson_php/pull/44 - a fix was waiting for review
