### ISSUE TITLE
Consider updating to simdjson 0.2.0

### ISSUE THREAD

**Issue by lemire** [crazyxman/simdjson_php#5]
The library simdjson has a new major release (0.2.0). Major changes:

* Support for 64-bit ARM processors, can run under iOS (iPhone).
* Runtime dispatching on x64 processors (switches to SSE on older x64 processors, uses AVX2 when available). Supports processors as far back as the Intel Westmere.
* More accurate number parsing.
* Fixes most warnings under Visual Studio.
* Several small bugs have been fixed.
* Better performance in some cases.
* Introduces a JSON Pointer interface https://tools.ietf.org/html/rfc6901
* Better and more specific error messages (with optional textual descriptions).
* valgrind clean.
* Unified code style (LLVM).

**Comment by crazyxman** [comment]
@lemire Thanks! I will update the native bindings.

**Comment by 1ma** [comment]
I'm very interested in this update, especially the wider range of CPU support.

I tried to update the amalgamation files to 0.2.1 and submit a PR but ultimately I couldn't make it work.

**Comment by lemire** [comment]
@1ma What was the issue?

Note: we made minor changes to the simdjson API.

**Comment by 1ma** [comment]
Yup I saw one, `ParsedJson::isValid()` was renamed to `ParsedJson::is_valid()`.

But I'm not fluent in C/C++, I don't have appropriate tooling for the language and after that I still had to fix these errors :sweat_smile: https://gist.github.com/1ma/7c7329ff57c9b70b02ad81b326311d08

Moreover, in `bindings.h` and `bindings.cpp` there is an `#ifdef __AVX2__` directive wrapping the whole content of the files that I guess that now should be removed or refactored somehow.

**Comment by lemire** [comment]
Yes! We don’t require AVX anymore.

**Comment by crazyxman** [comment]
Updated simdjson to version 0.2.1

**Comment by 1ma** [comment]
I cannot build the latest commit under Alpine Linux 3.10, getting these errors:

```
$ make
/bin/sh /root/simdjson_php/libtool --mode=compile cc  -I. -I/root/simdjson_php -DPHP_ATOM_INC -I/root/simdjson_php/include -I/root/simdjson_php/main -I/root/simdjson_php -I/usr/include/php7 -I/usr/include/php7/main -I/usr/include/php7/TSRM -I/usr/include/php7/Zend -I/usr/include/php7/ext -I/usr/include/php7/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /root/simdjson_php/simdjson.c -o simdjson.lo 
mkdir .libs
 cc -I. -I/root/simdjson_php -DPHP_ATOM_INC -I/root/simdjson_php/include -I/root/simdjson_php/main -I/root/simdjson_php -I/usr/include/php7 -I/usr/include/php7/main -I/usr/include/php7/TSRM -I/usr/include/php7/Zend -I/usr/include/php7/ext -I/usr/include/php7/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /root/simdjson_php/simdjson.c  -fPIC -DPIC -o .libs/simdjson.o
In file included from /root/simdjson_php/simdjson.c:23:
/root/simdjson_php/src/bindings.h:25:1: error: unknown type name 'namespace'; did you mean 'isspace'?
 namespace simdjsonphp {
 ^~~~~~~~~
 isspace
/root/simdjson_php/src/bindings.h:25:23: error: expected '=', ',', ';', 'asm' or '__attribute__' before '{' token
 namespace simdjsonphp {
                       ^
/root/simdjson_php/src/bindings.h:41:1: error: unknown type name 'bool'; did you mean '_Bool'?
 bool cplus_simdjson_isvalid(const char *json);
 ^~~~
 _Bool
/root/simdjson_php/simdjson.c:56:22: error: conflicting types for 'cplus_simdjson_isvalid'
 extern unsigned char cplus_simdjson_isvalid(const char *json);
                      ^~~~~~~~~~~~~~~~~~~~~~
In file included from /root/simdjson_php/simdjson.c:23:
/root/simdjson_php/src/bindings.h:41:6: note: previous declaration of 'cplus_simdjson_isvalid' was here
 bool cplus_simdjson_isvalid(const char *json);
      ^~~~~~~~~~~~~~~~~~~~~~
make: *** [Makefile:193: simdjson.lo] Error 1
```

Commit `a0e942d` from May 29th builds fine. If you want to try to reproduce, I started from a clean `alpine:3.10` Docker container and only installed the `git`, `build-base` and `php7-dev` packages.

**Comment by lemire** [comment]
@1ma  This looks like one is trying to compile C++ as if it were C... right?

**Comment by lemire** [comment]
@1ma It might be useful to open a distinct issue regarding build problems?

**Comment by 1ma** [comment]
You are right, sorry.

**Comment by lemire** [comment]
I suggest we close this issue.
