### ISSUE TITLE
Enable AppVeyor builds

### ISSUE THREAD

**Issue by TysonAndre** [crazyxman/simdjson_php#52]
`.appveyor.yml` is checked in but not enabled. This is building successfully and enabled on my fork - https://ci.appveyor.com/project/TysonAndre/simdjson-php/history

This would detect compilation errors on Windows

EDIT: It builds as https://ci.appveyor.com/project/TysonAndre/crazyxman-simdjson-php for the crazyxman/simdjson_php repo, but because I'm a collaborator, it won't create web hooks that trigger when PRs are updated, and I don't have access to project settings (through oauth or that)? https://help.appveyor.com/discussions/problems/5554-if-a-pull-request-is-open-before-adding-project-to-appveyor-even-new-commits-dont-trigger-builds

**Comment by crazyxman** [comment]
@TysonAndre  Ok, I have added appveyor to webhook
