### ISSUE TITLE
Consider setting up CI tests

### ISSUE THREAD

**Issue by lemire** [crazyxman/simdjson_php#7]
It should be possible to use circleci or drone to setup tests. At a minimum, one should check that the install process works.

**Comment by crazyxman** [comment]
Thanks! I will add CI tests

**Comment by sandrokeil** [comment]
@crazyxman Can you setup GitHub actions please to test the extension with different PHP versions. I think minimum PHP version 7.3 would be enough. So we have PHP 7.3, 7.4 and 8.0.

**Comment by lemire** [comment]
@sandrokeil I think somebody could do a pull request with actions.
